Update index.html
htmlacademy-htmlcss/1691051-technomart-30 pull request #2
Opened 2021-01-23 12:49 UTC by dalechka

2021-01-23 22:24 UTC, Zakamsky requested changes
Вижу что ты старалась, в целом все очень опрятно, комментариев много не не пугайся, часть из них просто советы.
Сложные блоки вроде слайдера и табов, если нет понимания как их сделать, можно оставить на будущее, и обсудить подробнее на какой нибудь консультации.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +          <img src="https://via.placeholder.com/17,51x18,97" width="17,51" height="18,97" alt="Иконка телефон">
тут сразу несколько моментов:
1. это все же декоративная иконка и кажется не стоит тащить ради нее лишние тжги в разметку, вполне можно сделать ее фоном.
2. сервис плэйсхолдеров не умеет в дробные числа и если посмотреть в опубликованной версии у нас тут картинка 1751 на 1897 =) но это на самом деле не важно.
3. что бы не мучаться с дробными размерами и упростить себе стилизацию обрати внимание что блок у которого ты нашла этот дробный размер, вложен внутрь фигуры (иконка ромбика), и можно при экспорте из фигмы вытащить весь этот ромбик и будет ровный размер 19 х 19 и иконка внутри него будет ровно размещена.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +        </p>
Совет:  для адреса можно использовать полезный тэг address.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +      <h1>Интернет-магазин «Техномарт»</h1>
Совет: если `<h1>` все равно скрытый, лучше разместить его выше всех остальных заголовках, это будет более логичная структура заголовков.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +              <input type="button" value="На любой вкус">
тут у нас маленькая проблемка. 
Во первых, `<input type="button" >` очень сильно устарел, его даже внутри формы лучше не использовать. Используй просто `<button type="button"></button>`
Во вторых, согласно тз это ссылка. Ссылка на соответсвующую категорию.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +              <img src="https://via.placeholder.com/44x65" width="44" height="65" alt="иконка материалов">
Ну и эти иконки тоже можно оставить как оформительские, для добавления из стилей. они ведь не несут никакой логической нагрузки?

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +      </section>
Обрати внимание на скрытые слои. Тут у нас слайдер с двумя слайдами. У каждого слайда есть своя оберточка внутри которой картинка текст и ссылка в виде кнопки. Все они лежат в общей обертке слайдера, и там же лежат общие для всех кнопки (вот тут ты абсолютно точно попала с тэгом) вперед-назад и еще мелкие круглые кнопочки в своей обертке.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +          </li>
неплохая реализация, но проблема в том что нельзя внутрь одного интерактивного элемента положить другой интерактивный элемент.
кроме того обрати внимание на стайлгайд - это такие же карточки как в каталоге, и по наведению там появляются еще две кнопки. Можно ссылкой обернуть только картинку например.
а конструкцию карточки используй одинаковую для этой и следующей страницы, что бы два раза штмл и стили не писать.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +              <span>New</span>
А вот этот лэйбл по тз должен быть доступен для любой картjxки без вмешательства в штмл. Предлагаю сделать его псевдоэлементом. один раз напишешь стили и лэйбл появится у каждой карточки у которой будет класс .new

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +        <img src="https://via.placeholder.com/220x145" width="220" height="145" alt="Логотип Metabo">
А эти карточки по тз - ссылки. вот тут можно не мудрствуя просто обернуть картинку ссылкой.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +            <label for="filter-credit">Кредит</label>
Так... а что мы тут вводим? аааа это кнопки - переключатели. такая секция называется табы. обрати внимание на скрытые слои. Это чем то похоже на слайдер, но без стрелок. для каждой кнопки есть свой слой который будет видим, когда кнопка активна.

2021-01-23 22:24 UTC, Zakamsky commented on index.html
> +        <img src="https://via.placeholder.com/468x261" width="468" height="261" alt="Изображение грузовика">
ну и тут наверное лучше сделать три блока внутри которых все табы со скрытых слоев - доставка, гарантии и кредит. Т.е. по блоку на слой, как в слайдере.

2021-01-25 06:28 UTC, dalechka commented on index.html
> +      <i>Интернет-магазин строительных материалов и инструментов для ремонта</i>
Здесь решила оставить тег р, а оформление делать в css

2021-01-25 06:39 UTC, dalechka commented on index.html
> +          <img src="https://via.placeholder.com/17,51x18,97" width="17,51" height="18,97" alt="Иконка телефон">
Получается, здесь не нужен тег alt? Если и побьется картинка - ничего страшного

2021-01-25 07:04 UTC, dalechka commented on index.html
> +      </section>
Слайдер пока оставлю, не смогла самостоятельно разобраться с этими переключателями слайдов((((

2021-01-25 07:20 UTC, dalechka commented on index.html
> +            <label for="filter-credit">Кредит</label>
оставлю пока эти компоненты списком... Слайдер и табы мне пока неподвластны)))

2021-01-25 07:22 UTC, dalechka commented on index.html
> +        <img src="https://via.placeholder.com/468x261" width="468" height="261" alt="Изображение грузовика">
Здесь пока менять не буду...

2021-01-27 00:08 UTC, Zakamsky commented on index.html
> +          <img src="https://via.placeholder.com/17,51x18,97" width="17,51" height="18,97" alt="Иконка телефон">
Давай порассуждаем вместе, представь что совсем ничего не отобразилось, что поменяется? останется видным и понятным телефон, на него можно буде кликнуть и позвонить. Т.е. по сути иконка тут просто для красоты? (как по сути 99% иконок на сайте, есть у вас хорошая статья в след главе про разделение контента и оформления, а пока давай оставим этот вопрос до след главы.)

2021-01-27 00:10 UTC, Zakamsky commented on index.html
> +        </p>
`<address>` 😇

2021-01-27 00:31 UTC, Zakamsky requested changes

2021-01-27 00:31 UTC, Zakamsky commented on catalog.html
> +          <adress>Адрес: г. Санкт-Петербург, Б. Конюшенная, д. 19/8</adress>
На обеих страницах исправь пожалуйста опечатку в тэге.

2021-01-27 00:31 UTC, Zakamsky commented on catalog.html
> +
А почему эти поля лежат в отдельной форме? а как они будут отправляться на сервер, тоже отдельно?
Лучше все таки поместить все поля фильтра в одну форму т.к. это одна сущность.
Кстати у этих полей потерян один атрибут из за чего их данные не улетают на сервер, но я уверен что ты без труда догадаешься какой, т.к. в других полях (во второй форме) он есть.
Но если вдруг нет - спроси у меня.

2021-01-27 00:31 UTC, Zakamsky commented on catalog.html
> +                    <label for="mains-power">Сетевые</label>
Отличный пример радиокнопок. Очень часто путают их с чекбоксами, молодец что разобралась в отличиях.

2021-01-27 00:31 UTC, Zakamsky commented on catalog.html
> +          </a>
Секция без заголовка... а на первой странице я проглядел? похоже да, исправь на обоих пожалуйста.

2021-01-27 00:31 UTC, Zakamsky commented on catalog.html
> +              <li>
снова секция без заголовка... 
В каждой секции должен быть заголовок, хотя бы незримый.

2021-01-27 00:31 UTC, Zakamsky commented on index.html
> +            <label>Кредит</label>
лэйблы остались, надо подчистить, это же элемент формы он не может просто так тут находиться. Тем более это интерактивные элементы. Идеально подошла бы кнопка...

2021-01-27 09:28 UTC, dalechka commented on catalog.html
> +
Затупила... добавила fieldset

2021-01-27 19:10 UTC, Zakamsky reviewed
Вот теперь все хорошо! Давай в спокойном темпе двигаться дальше.

2021-01-27 19:10 UTC, merged